In [1]:
#we are going to filter some data out

In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("data.csv")

In [6]:
df.head()

,EmployeeID,Name,Age,Department,Salary,JoiningDate,Phone,Email,City
0,101,Alice Johnson,28.0,IT,65000,2022-01-15,9.841000e+09,alice@gmail.com,Kathmandu
1,102,Bob Smith,35.0,HR,55000,2021-03-10,9.841000e+09,bob@gmail.com,Pokhara
2,103,Charlie Brown,42.0,Finance,72000,2019-07-20,9.841000e+09,charlie@gmail.com,Lalitpur
3,104,David Wilson,29.0,IT,68000,2023-05-11,NaN,david@gmail.com,Bhaktapur
4,105,Emma Davis,31.0,Marketing,50000,2020-09-18,9.841000e+09,emma@gmail.com,Kathmandu

In [8]:
df[df["Age"]>20] #here we will print the dataset whose ages are greateer than 20

,EmployeeID,Name,Age,Department,Salary,JoiningDate,Phone,Email,City
0,101,Alice Johnson,28.0,IT,65000,2022-01-15,9.841000e+09,alice@gmail.com,Kathmandu
1,102,Bob Smith,35.0,HR,55000,2021-03-10,9.841000e+09,bob@gmail.com,Pokhara
2,103,Charlie Brown,42.0,Finance,72000,2019-07-20,9.841000e+09,charlie@gmail.com,Lalitpur
3,104,David Wilson,29.0,IT,68000,2023-05-11,NaN,david@gmail.com,Bhaktapur
4,105,Emma Davis,31.0,Marketing,50000,2020-09-18,9.841000e+09,emma@gmail.com,Kathmandu
6,107,Grace Lee,26.0,HR,48000,2024-02-14,9.841000e+09,grace@gmail.com,Pokhara
7,108,Henry Walker,39.0,IT,82000,2017-04-30,9.841000e+09,henry@gmail.com,Dharan
8,109,Isabella Hall,33.0,Marketing,59000,2022-08-05,NaN,isabella@gmail.com,Kathmandu
9,110,Jack White,45.0,Finance,91000,2016-06-12,9.841000e+09,jack@gmail.com,Biratnagar
10,111,Karen Young,27.0,Sales,47000,2023-01-09,9.841000e+09,karen@gmail.com,Hetauda
11,112,Liam Scott,36.0,Sales,61000,2021-12-19,9.841000e+09,liam@gmail.com,Chitwan
12,113,Mia Green,24.0,HR,46000,2024-04-25,9.841000e+09,mia@gmail.com,Lalitpur
13,114,Noah King,38.0,Marketing,64000,2020-07-17,9.841000e+09,noah@gmail.com,Kathmandu
14,115,Olivia Adams,30.0,IT,70000,2022-10-08,9.841000e+09,olivia@gmail.com,Pokhara
15,116,Peter Parker,41.0,Finance,86000,2019-01-29,NaN,peter@gmail.com,Dharan
16,117,Quinn Harris,29.0,Sales,53000,2023-06-21,9.841000e+09,quinn@gmail.com,Bhaktapur
17,118,Rachel Clark,34.0,IT,69000,2021-08-15,9.841000e+09,rachel@gmail.com,Butwal
18,119,Sam Lewis,32.0,HR,57000,2020-02-11,9.841000e+09,sam@gmail.com,Hetauda
19,120,Tina Martin,27.0,Marketing,51000,2024-05-05,9.841000e+09,tina@gmail.com,Kathmandu
20,121,Alice Johnson,28.0,IT,65000,2022-01-15,9.841000e+09,alice@gmail.com,Kathmandu
22,123,Wendy Moore,37.0,Finance,78000,2018-03-16,9.841000e+09,wendy@gmail.com,Biratnagar
23,124,Xavier Hill,25.0,IT,62000,2024-01-10,9.841000e+09,xavier@gmail.com,Lalitpur
24,125,Yara Cooper,40.0,Marketing,73000,2017-12-01,9.841000e+09,yara@gmail.com,Dharan
25,126,Zack Evans,29.0,HR,52000,2023-07-27,9.841000e+09,zack@gmail.com,Kathmandu

In [9]:
#if we want to perfom the multiple conditions

In [14]:
df(df["Age">20)& (df["Deparment"]=="IT"]]

TypeError: '>' not supported between instances of 'str' and 'int'