In [1]:
#EDA- it allows us to check the statistical distrubtion of variables, spot extreme anomolies or outliners and calculate how different mediacl features coorelate with one another.

In [2]:
#we will be exploring the data set of the health care system.

In [3]:
import pandas as pd
import numpy as np

In [4]:
df_health=pd.read_csv("health.csv")

In [6]:
df_health.head()

,Patient_ID,Age,BMI,Systolic_BP,Diastolic_BP,Cholesterol,Glucose,Heart_Rate,Exercise_Hours_Per_Week,Hospital_Visits_Last_Year,Disease_Risk_Score
0,P001,69,19.0,134,76,269,100,78,4.3,0,54.3
1,P002,32,25.9,90,74,235,129,73,1.3,2,54.8
2,P003,78,28.5,146,70,284,105,75,7.0,1,67.6
3,P004,38,29.3,119,72,275,122,95,0.6,2,50.6
4,P005,41,26.4,127,70,220,124,63,4.9,2,40.0

In [8]:
df_health.tail()

,Patient_ID,Age,BMI,Systolic_BP,Diastolic_BP,Cholesterol,Glucose,Heart_Rate,Exercise_Hours_Per_Week,Hospital_Visits_Last_Year,Disease_Risk_Score
245,P246,36,27.5,110,70,258,114,77,3.0,2,50.7
246,P247,21,28.6,108,70,227,126,69,3.7,1,39.1
247,P248,52,34.7,118,70,262,90,91,3.3,1,50.7
248,P249,81,30.9,153,76,305,100,77,4.4,1,66.0
249,P250,66,26.5,131,81,271,104,79,4.0,4,61.2

In [10]:
#generate descriptive statistics for key clinical metrics

In [12]:
clinical_summary = df_health[["Age","BMI","Cholesterol","Disease_Risk_Score"]].describe()

In [15]:
print("__HealthCare Descriptive Statistics__")
print(clinical_summary)

__HealthCare Descriptive Statistics__
             Age         BMI  Cholesterol  Disease_Risk_Score
count  250.00000  250.000000   250.000000          250.000000
mean    50.42000   26.813600   256.872000           51.534800
std     20.17662    4.821952    36.429715           12.793464
min     18.00000   11.900000   164.000000           18.900000
25%     33.00000   23.700000   228.250000           41.050000
50%     50.00000   26.600000   255.000000           52.150000
75%     69.00000   30.400000   286.000000           60.450000
max     84.00000   41.300000   344.000000           83.000000

#describe automatically computes the count, mean, standard deviation, mini, max, median and interquartile ranges for the selected clinical columns simultaneously.

In [16]:
#corrrelation analysis

In [17]:
#compute the pearson correlation matrix for numerical features.

In [21]:
correlation_matrix= df_health[["Age","BMI","Cholesterol","Glucose","Exercise_Hours_Per_Week","Disease_Risk_Score"]].corr()

In [22]:
print("--Clinical Metrics Correlation Matrix--")
print(correlation_matrix)

--Clinical Metrics Correlation Matrix--
                              Age       BMI  Cholesterol   Glucose  \
Age                      1.000000  0.040006     0.750109  0.067957
BMI                      0.040006  1.000000     0.313319  0.423070
Cholesterol              0.750109  0.313319     1.000000  0.193627
Glucose                  0.067957  0.423070     0.193627  1.000000
Exercise_Hours_Per_Week -0.049590  0.011361    -0.080012 -0.028300
Disease_Risk_Score       0.682078  0.276206     0.651560  0.275322

                         Exercise_Hours_Per_Week  Disease_Risk_Score
Age                                    -0.049590            0.682078
BMI                                     0.011361            0.276206
Cholesterol                            -0.080012            0.651560
Glucose                                -0.028300            0.275322
Exercise_Hours_Per_Week                 1.000000           -0.241321
Disease_Risk_Score                     -0.241321            1.000000